export const INITIAL_FETCH = "INITIAL_FETCH";
export const AUTH_REQUEST = "AUTH_REQUEST";

// AUTH

export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_LOGIN = "USER_LOGIN";
export const FETCH_USER = "FETCH_USER";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

// POST
export const POST_INVITE = "POST_INVITE";

// USERS
export const FETCH_USERS = "FETCH_USERS";
export const FRIEND_REQUEST = "FRIEND_REQUEST";
export const FETCH_FRIEND_REQUESTS = "FETCH_FRIEND_REQUESTS";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const FETCH_FRIENDS = "FETCH_FRIENDS";

// Invites
export const COLLECT_INVITE_CATEGORY_STATE = "COLLECT_INVITE_CATEGORY_STATE";
export const COLLECT_INVITE_DETAILS_STATE = "COLLECT_INVITE_DETAILS_STATE";
export const COLLECT_INVITE_INVITED_USERS_STATE =
  "COLLECT_INVITE_INVITED_USERS_STATE";
